
targets:
  $default:
    builders:
      injectable_generator|injectable_config_builder:
        options:
          prefer_relative_imports: true
          outputs:
             lib/generated/injector:
#            test/injector/injector:
#              include_inputs_from:
#                - lib
#          auto_register: true
#          # auto registers any class with a name matches the given pattern
#          class_name_pattern:
#            "Service$|Repository$|Bloc$"
#          # auto registers any class inside a file with a
#          # name matches the given pattern
#          file_name_pattern: "_service$|_repository$|_bloc$"